// generated by umi
declare global {
const React: typeof import('react');

const computed: typeof import('vue')['computed'];
const ref: typeof import('vue')['ref'];
const defineStore: typeof import('pinia')['defineStore'];
const useCounterStore: typeof import('@/stores/count')['useCounterStore'];
const styles: any;


}
export {}
